<?php
header("Content-Type: application/json; charset=utf-8");
header("X-Powered-By: Express");
header("Access-Control-Allow-Origin: *");
header("Vary: Accept-Encoding");

echo '{
	"rewards": [{
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 11,
		"bracket_end": 50,
		"base_quantity": 1,
		"base_type": "MORTY",
		"sort_order": 1,
		"base_parameters": {
			"ids": ["MortyBronzeAge"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 201,
		"bracket_end": 400,
		"base_quantity": 1,
		"base_type": "MORTY",
		"sort_order": 1,
		"base_parameters": {
			"ids": ["MortyStoneAge"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 651,
		"bracket_end": 1000,
		"base_quantity": 1,
		"base_type": "COUPON",
		"sort_order": 1,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 401,
		"bracket_end": 650,
		"base_quantity": 1,
		"base_type": "MORTY",
		"sort_order": 1,
		"base_parameters": {
			"ids": ["MortyStoneAge"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 101,
		"bracket_end": 200,
		"base_quantity": 1,
		"base_type": "MORTY",
		"sort_order": 1,
		"base_parameters": {
			"ids": ["MortyStoneAge"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 1001,
		"bracket_end": 1500,
		"base_quantity": 1,
		"base_type": "ITEM",
		"sort_order": 1,
		"base_parameters": {
			"ids": ["ItemSerum"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 51,
		"bracket_end": 100,
		"base_quantity": 1,
		"base_type": "MORTY",
		"sort_order": 1,
		"base_parameters": {
			"ids": ["MortyBronzeAge"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 1,
		"bracket_end": 1,
		"base_quantity": 1,
		"base_type": "MORTY",
		"sort_order": 1,
		"base_parameters": {
			"ids": ["MortyIronAge"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 3,
		"bracket_end": 3,
		"base_quantity": 1,
		"base_type": "MORTY",
		"sort_order": 1,
		"base_parameters": {
			"ids": ["MortyIronAge"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 1501,
		"bracket_end": 2000,
		"base_quantity": 1,
		"base_type": "ITEM",
		"sort_order": 1,
		"base_parameters": {
			"ids": ["ItemSerum"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 2,
		"bracket_end": 2,
		"base_quantity": 1,
		"base_type": "MORTY",
		"sort_order": 1,
		"base_parameters": {
			"ids": ["MortyIronAge"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 4,
		"bracket_end": 10,
		"base_quantity": 1,
		"base_type": "MORTY",
		"sort_order": 1,
		"base_parameters": {
			"ids": ["MortyIronAge"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 3,
		"bracket_end": 3,
		"base_quantity": 4,
		"base_type": "COUPON",
		"sort_order": 2,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 101,
		"bracket_end": 200,
		"base_quantity": 2,
		"base_type": "COUPON",
		"sort_order": 2,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 201,
		"bracket_end": 400,
		"base_quantity": 2,
		"base_type": "COUPON",
		"sort_order": 2,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 2,
		"bracket_end": 2,
		"base_quantity": 5,
		"base_type": "COUPON",
		"sort_order": 2,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 401,
		"bracket_end": 650,
		"base_quantity": 3,
		"base_type": "ITEM",
		"sort_order": 2,
		"base_parameters": {
			"ids": ["ItemSerum"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 401,
		"bracket_end": 650,
		"base_quantity": 1,
		"base_type": "COUPON",
		"sort_order": 2,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 4,
		"bracket_end": 10,
		"base_quantity": 3,
		"base_type": "COUPON",
		"sort_order": 2,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 51,
		"bracket_end": 100,
		"base_quantity": 2,
		"base_type": "COUPON",
		"sort_order": 2,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 1,
		"bracket_end": 1,
		"base_quantity": 7,
		"base_type": "COUPON",
		"sort_order": 2,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 651,
		"bracket_end": 1000,
		"base_quantity": 2,
		"base_type": "ITEM",
		"sort_order": 2,
		"base_parameters": {
			"ids": ["ItemSerum"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 11,
		"bracket_end": 50,
		"base_quantity": 3,
		"base_type": "COUPON",
		"sort_order": 2,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 101,
		"bracket_end": 200,
		"base_quantity": 2,
		"base_type": "ITEM",
		"sort_order": 2,
		"base_parameters": {
			"ids": ["ItemGreatSerum"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 1,
		"bracket_end": 1,
		"base_quantity": 1,
		"base_type": "ITEM",
		"sort_order": 3,
		"base_parameters": {
			"ids": ["ItemSensationalSerum"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 101,
		"bracket_end": 200,
		"base_quantity": 1,
		"base_type": "ITEM",
		"sort_order": 3,
		"base_parameters": {
			"ids": ["ItemMegaSeedSpeed"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 11,
		"bracket_end": 50,
		"base_quantity": 3,
		"base_type": "ITEM",
		"sort_order": 3,
		"base_parameters": {
			"ids": ["ItemGreatSerum"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 3,
		"bracket_end": 3,
		"base_quantity": 1,
		"base_type": "ITEM",
		"sort_order": 3,
		"base_parameters": {
			"ids": ["ItemSensationalSerum"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 51,
		"bracket_end": 100,
		"base_quantity": 2,
		"base_type": "ITEM",
		"sort_order": 3,
		"base_parameters": {
			"ids": ["ItemGreatSerum"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 2,
		"bracket_end": 2,
		"base_quantity": 1,
		"base_type": "ITEM",
		"sort_order": 3,
		"base_parameters": {
			"ids": ["ItemSensationalSerum"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 201,
		"bracket_end": 400,
		"base_quantity": 2,
		"base_type": "ITEM",
		"sort_order": 3,
		"base_parameters": {
			"ids": ["ItemGreatSerum"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 4,
		"bracket_end": 10,
		"base_quantity": 1,
		"base_type": "ITEM",
		"sort_order": 4,
		"base_parameters": {
			"ids": ["ItemSensationalSerum"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 2,
		"bracket_end": 2,
		"base_quantity": 3,
		"base_type": "ITEM",
		"sort_order": 4,
		"base_parameters": {
			"ids": ["ItemMegaSeedSpeed"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 3,
		"bracket_end": 3,
		"base_quantity": 3,
		"base_type": "ITEM",
		"sort_order": 4,
		"base_parameters": {
			"ids": ["ItemMegaSeedSpeed"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 51,
		"bracket_end": 100,
		"base_quantity": 1,
		"base_type": "ITEM",
		"sort_order": 4,
		"base_parameters": {
			"ids": ["ItemMegaSeedSpeed"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 1,
		"bracket_end": 1,
		"base_quantity": 4,
		"base_type": "ITEM",
		"sort_order": 4,
		"base_parameters": {
			"ids": ["ItemMegaSeedSpeed"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 3,
		"bracket_end": 3,
		"base_quantity": 1,
		"base_type": "ITEM",
		"sort_order": 5,
		"base_parameters": {
			"ids": ["ItemMegaSeedAttack"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 2,
		"bracket_end": 2,
		"base_quantity": 1,
		"base_type": "ITEM",
		"sort_order": 5,
		"base_parameters": {
			"ids": ["ItemMegaSeedAttack"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 11,
		"bracket_end": 50,
		"base_quantity": 1,
		"base_type": "ITEM",
		"sort_order": 5,
		"base_parameters": {
			"ids": ["ItemMegaSeedSpeed"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 1,
		"bracket_end": 1,
		"base_quantity": 2,
		"base_type": "ITEM",
		"sort_order": 5,
		"base_parameters": {
			"ids": ["ItemMegaSeedAttack"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 4,
		"bracket_end": 10,
		"base_quantity": 2,
		"base_type": "ITEM",
		"sort_order": 5,
		"base_parameters": {
			"ids": ["ItemMegaSeedSpeed"]
		}
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 101,
		"bracket_end": 200,
		"base_quantity": 900,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 4,
		"bracket_end": 10,
		"base_quantity": 1300,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 201,
		"bracket_end": 400,
		"base_quantity": 800,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 3501,
		"bracket_end": 8000,
		"base_quantity": 100,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 651,
		"bracket_end": 1000,
		"base_quantity": 600,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 2,
		"bracket_end": 2,
		"base_quantity": 1750,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 51,
		"bracket_end": 100,
		"base_quantity": 1000,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 11,
		"bracket_end": 50,
		"base_quantity": 1100,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 2501,
		"bracket_end": 3500,
		"base_quantity": 150,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 1501,
		"bracket_end": 2000,
		"base_quantity": 400,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 1,
		"bracket_end": 1,
		"base_quantity": 2000,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 2001,
		"bracket_end": 2500,
		"base_quantity": 200,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 1001,
		"bracket_end": 1500,
		"base_quantity": 500,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 401,
		"bracket_end": 650,
		"base_quantity": 700,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}, {
		"rewards_name": "REWARDS_LIVE_Through_Ages_Morty",
		"bracket_start": 3,
		"bracket_end": 3,
		"base_quantity": 1500,
		"base_type": "COIN",
		"sort_order": 1000,
		"base_parameters": null
	}]
}';